### ISSUE TITLE
Задание 4 и 5 (Федя)

### ISSUE THREAD

**Issue by Zener085** [Zeneriode/EGE-INF-MAMAMIA#6]
Выполнить задачи 10, 14 [отсюда](https://inf-ege.sdamgia.ru/test?theme=369)
Выполнить задачу 14 [отсюда](https://inf-ege.sdamgia.ru/test?theme=232)
Выполнить задачу 18 [отсюда](https://inf-ege.sdamgia.ru/test?theme=362)
Выполнить задачи 6, 15 [отсюда](https://inf-ege.sdamgia.ru/test?theme=221)

**Comment by Locivo** [comment]
10, 14 ответы 24
Сайт не работает
18 - 126. Код такой же как и на прошлом занятии был
Сайт не работает
![image](https://user-images.githubusercontent.com/109408910/186080036-b6d65d25-1709-462d-865d-f9e5d6f295da.png)
